### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by szabgab**
To run the tests on every push and every pull-request.
This PR is part of my [Daily CI](https://dev.to/szabgab/the-2022-december-ci-challenge-5dof) project

### CODE REVIEW

**Comment by szabgab** [comment]
And [here](https://dev.to/szabgab/day-20-skeletons-are-good-but-can-be-misleading-ci-for-the-draftjshtml-ruby-gem--5gke) is the article about this PR.

**Review by dugancathal — APPROVED** [review]
Thank you for doing this! I had the tests working on travis for the main-branch builds, but this, if I'm understanding correctly will also run them on PRs. That's awesome!

Cheers!

**Comment by dugancathal** [comment]
image

💥 This is great - appreciate ya, @szabgab!

**Comment by szabgab** [comment]
Yes.
You can also add more version of ruby to the matrix.
If this project is supposed to work on Window and macOS as well, I can also send you a PR configuring those, though especially for windows I won't be able to use `./bin/setup`.

**Pull request merged**
